### ISSUE TITLE
CLI - should reuse docker image layers and skip upload when no changes

### ISSUE THREAD

**Issue by dpatekar** [beamable/BeamableProduct#3478] opened 2024-06-11 13:21 UTC
`beam services deploy` seems to upload the service images on every run, even if there are no changes.

**Comment by cdhanna** [comment] 2024-06-11 13:57
first thing to check, if we build the docker image, then rebuild the docker image, are the resulting image ids the same? If yes, then we shouldn't re-upload the service. This is a simple string image-id comparison. 

Is there a way to get the resulting hash imageId of a tarball WITHOUT doing the docker build? 

----

Investigate the layer hash changes between runs... Why are they? 

we should verify that the `CreateTarballForDirectory` function's preprocess,
```cs
		foreach (var file in files)
		{
			if (file.Contains("/bin/")) continue;
			if (file.Contains("/obj/")) continue;
			filteredFiles.Add(file);
		}
```

in working as intended...

**Comment by cdhanna** [comment] 2024-06-11 13:59
another thing we can do is check if the individual layers are uploaded. Talk to Ben!

**Comment by cdhanna** [comment] 2024-08-29 14:01
This is related to https://github.com/beamable/BeamableProduct/issues/3556 

We should explore what happens now that we don't use the docker API to do build images.

**Comment by cdhanna** [comment] 2024-12-06 15:25
this was resolved with plan/release

**Closed by cdhanna** 2024-12-06 15:25 UTC
